[install]
# Use npm registry for better compatibility
registry = "https://registry.npmjs.org/"

# Skip optional dependencies that cause issues
optional = false

# Use exact versions to avoid conflicts
exact = false

# Prefer npm over bun for problematic packages
prefer-npm = ["rollup", "@rollup/rollup-linux-x64-gnu"]

[install.scopes]
# Force specific versions for problematic packages
"@rollup" = { version = "4.9.5" }
