// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jqvxedomqlanafjpskni.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpxdnhlZG9tcWxhbmFmanBza25pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwOTUxMDMsImV4cCI6MjA2ODY3MTEwM30.ul4pDoJh8-AkOxFe6iMeuWA5E93_-EpucH4dxHB5e7M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});